// ====== Between Us — question bank ======
// Every question now carries a "level" from 1 (light) to 4 (vulnerable).
// Levels power Conversation Mode, which orders a deck so it starts easy
// and gradually deepens instead of pure random shuffle.
//
// CATEGORY_META gives each category a label, emoji, and an "ink stamp"
// color for the card's corner label. "mix" has no question list of its
// own — it's built by combining every category at runtime.

export const CATEGORY_META = {
  mix: { emoji: "🎲", label: "Random Mix", color: "#c9a15a" },
  love: { emoji: "❤️", label: "Love", color: "#9c3348" },
  friendship: { emoji: "😊", label: "Friendship", color: "#2f6f65" },
  family: { emoji: "👨‍👩‍👧", label: "Family", color: "#a1653d" },
  deep: { emoji: "🔥", label: "Deep", color: "#3d3a75" },
  funny: { emoji: "😂", label: "Funny", color: "#b8862e" },
  party: { emoji: "🎉", label: "Party", color: "#c2437a" },
  firstImpressions: { emoji: "🎯", label: "First Impressions", color: "#4a6fa5" },
  wouldYouRather: { emoji: "🧠", label: "Would You Rather", color: "#3c6b3f" },
  confessions: { emoji: "💭", label: "Confessions", color: "#6b3d6b" },
  dares: { emoji: "😈", label: "Dares", color: "#a1452a" },
  wyd: { emoji: "🤔", label: "What Would You Do", color: "#45566b" },
  vote: { emoji: "🗳️", label: "Vote Prompts", color: "#7a4fba" },
  custompack: { emoji: "📦", label: "Custom Pack", color: "#5b6b8c" },
};

function q(text, level) {
  return { text, level };
}

export const QUESTIONS = {
  love: [
    q("What was the moment you knew you had feelings for me?", 2),
    q("What's one small thing I do that makes you feel loved?", 1),
    q("What's your love language, and do you think I speak it well?", 2),
    q("What's a memory of us you'd want to relive exactly as it happened?", 2),
    q("What's something you find attractive that most people wouldn't guess?", 2),
    q("What's a fear you have about us, if any?", 4),
    q("What's the most romantic thing you can imagine us doing?", 1),
    q("When do you feel closest to me?", 2),
    q("What's a song that reminds you of me?", 1),
    q("What's something you want us to try together that we haven't yet?", 2),
    q("What do you think is our biggest strength as a couple?", 2),
    q("What's one thing you hope never changes between us?", 2),
    q("How do you like to be comforted when you're upset?", 2),
    q("What's a habit of mine you secretly love?", 1),
    q("Where do you picture us in five years?", 3),
    q("What's something you've never told me but want to?", 4),
  ],
  friendship: [
    q("What's the first thing you noticed about me when we met?", 1),
    q("What's one thing I do that annoys you (be honest)?", 2),
    q("What's your favorite memory with me?", 1),
    q("If I disappeared tomorrow, what would you miss most?", 3),
    q("What's a quality of mine you wish you had?", 2),
    q("When did you know we'd actually be close?", 2),
    q("What's something you've never told me because it felt awkward?", 3),
    q("What's the funniest thing we've been through together?", 1),
    q("How would you describe us in three words?", 1),
    q("What's a piece of advice I gave you that actually stuck?", 2),
    q("What's something you think I'm better at than I realize?", 2),
    q("If we started a business together, what would it be?", 1),
    q("What's a habit of mine that low-key influenced you?", 2),
    q("What do you think people misunderstand about me?", 3),
    q("What's one thing you'd want to do together before we're 80?", 2),
    q("Who would play me in a movie about your life?", 1),
  ],
  family: [
    q("What's a family tradition you actually love?", 1),
    q("Who do you take after most in your family, and how?", 1),
    q("What's a rule your family had growing up that you still follow?", 1),
    q("What's your favorite family holiday memory?", 1),
    q("What's something your family does that other families would find strange?", 1),
    q("Who's the funniest person in your family?", 1),
    q("What's a lesson your parents (or whoever raised you) taught you that stuck?", 2),
    q("What's a family recipe or dish you'd never want to lose?", 1),
    q("What's something you hope to do differently than your parents did?", 3),
    q("What's your earliest childhood memory?", 2),
    q("If you could bring back one family gathering exactly as it was, which one?", 2),
    q("What's a nickname from your family you actually don't mind?", 1),
  ],
  deep: [
    q("What's something nobody in your life fully knows about you?", 4),
    q("What's your biggest regret so far?", 3),
    q("If today were your last day, who's the first person you'd call?", 3),
    q("What's your biggest, most honest dream?", 3),
    q("What's something you're scared of that you rarely admit?", 4),
    q("What belief did you hold strongly that you later changed your mind about?", 2),
    q("What's something you needed to hear from someone, but never did?", 4),
    q("What does \"home\" mean to you?", 2),
    q("What's a moment that quietly changed who you are?", 3),
    q("What do you think is the point of your life, if there is one?", 3),
    q("What's something you forgive yourself for now that you didn't used to?", 4),
    q("Who shaped you the most, for better or worse?", 3),
    q("What are you most proud of that no one really gave you credit for?", 2),
    q("What's a question you're afraid to ask yourself?", 4),
    q("What would you want people to say about you after you're gone?", 3),
    q("What's something you're still healing from?", 4),
  ],
  funny: [
    q("What's your most embarrassing moment that you can laugh about now?", 1),
    q("What's your weirdest habit that almost nobody knows about?", 1),
    q("Which celebrity would survive a zombie apocalypse, and why?", 1),
    q("If animals could talk, which one would be the rudest?", 1),
    q("What's the dumbest thing you've ever argued about?", 1),
    q("What's a food combination you love that grosses other people out?", 1),
    q("What's the most ridiculous excuse you've ever used?", 1),
    q("If your life had a laugh track, what moment would trigger it most?", 1),
    q("What's a weird talent you have that's basically useless?", 1),
    q("What's the worst haircut or outfit you've ever had?", 1),
    q("What's a lie you told as a kid that somehow worked?", 1),
    q("If you had a theme song that played every time you walked in, what would it be?", 1),
    q("What's the strangest dream you remember having?", 1),
    q("What's a word you can never pronounce correctly?", 1),
    q("What's the most chaotic thing that's happened on a night out?", 1),
    q("If you were a meme, which one would you be?", 1),
  ],
  party: [
    q("What's your go-to karaoke song?", 1),
    q("What's the best party you've ever been to?", 1),
    q("Dance floor or snack table — where do we find you?", 1),
    q("What's a party trick or talent you can pull out on command?", 1),
    q("What's the worst party foul you've ever witnessed?", 1),
    q("If tonight had a theme, what would it be?", 1),
    q("What song instantly gets you on the dance floor?", 1),
    q("What's your late-night snack of choice?", 1),
    q("Who's more likely to start a conga line — you or me?", 1),
    q("What's the most fun you've had on a random night out?", 1),
    q("If we threw a party right now, who's the first person you'd invite?", 1),
    q("What's your signature drink order (alcoholic or not)?", 1),
  ],
  firstImpressions: [
    q("What was your actual first impression of me?", 2),
    q("What do you think I noticed about you first?", 2),
    q("Did you like me right away, or did I grow on you?", 2),
    q("What almost stopped us from becoming close?", 3),
    q("What's something about me that surprised you once you got to know me?", 2),
    q("If you had to guess my job from a first meeting, what would you have guessed?", 1),
    q("What do you think strangers assume about me that's wrong?", 2),
    q("What's the first thing people usually notice about you?", 1),
    q("Would you have approached me first, or waited?", 1),
    q("What's a first impression of someone that turned out to be completely wrong?", 1),
    q("What do you remember about the outfit or vibe I had when we met?", 1),
    q("Looking back, what took you the longest to figure out about me?", 3),
  ],
  wouldYouRather: [
    q("Lose your phone forever or never eat your favorite food again?", 1),
    q("Be invisible or be able to read minds?", 1),
    q("Live underwater or live on Mars?", 1),
    q("Always know when someone's lying, or always get away with lying yourself?", 1),
    q("Have unlimited money or unlimited time?", 1),
    q("Relive your favorite year or skip straight to a guaranteed happy future?", 1),
    q("Be famous for something embarrassing or unknown but respected?", 1),
    q("Never use social media again or never watch another movie or show again?", 1),
    q("Always say what you're thinking or never speak again for a day?", 1),
    q("Travel to the past or the future?", 1),
    q("Have the ability to fly or be super strong?", 1),
    q("Eat one meal for the rest of your life or never eat your favorite meal again?", 1),
    q("Live without music or live without your phone?", 1),
    q("Talk to animals or speak every human language fluently?", 1),
    q("Have a rewind button on life or a pause button?", 1),
    q("Know how you'll die or know when you'll die?", 2),
  ],
  confessions: [
    q("What's something you've done that you've never told anyone?", 4),
    q("What's a small lie you've told that turned into a bigger one?", 2),
    q("What's something you pretend to like but actually don't?", 1),
    q("What's a time you took credit for something you didn't fully do?", 2),
    q("What's something you're jealous of, even if it's silly?", 2),
    q("What's a secret talent you've never shown anyone?", 1),
    q("What's something you did as a kid that would embarrass you now?", 1),
    q("What's a rule you break more often than you'd admit?", 2),
    q("What's something you judged someone for, then realized you do too?", 3),
    q("What's the last thing you cried about?", 3),
    q("What's something you say you're fine with, but actually aren't?", 4),
    q("What's a text or message you regret sending?", 2),
    q("What's a habit you have that you're low-key trying to hide?", 2),
    q("What's something you wish you could redo differently?", 3),
  ],
  dares: [
    q("Send the last photo in your camera roll, no explanation.", 2),
    q("Do your best impression of the other player right now.", 1),
    q("Text a random contact \"I have something important to tell you,\" then leave them hanging.", 1),
    q("Speak in an accent of your choice for the next two questions.", 1),
    q("Show your most-used emoji and explain why it's your go-to.", 1),
    q("Do 10 jumping jacks before answering the next question.", 1),
    q("Let the other player post one word as your status for the next hour.", 1),
    q("Sing the chorus of the last song you listened to.", 1),
    q("Show the last thing you searched on your phone, if it's not private.", 1),
    q("Do your best dance move for 10 seconds.", 1),
    q("Let the other player scroll your camera roll for 10 seconds.", 2),
    q("Talk in slow motion for your next answer.", 1),
    q("Attempt to lick your elbow. Yes, really.", 1),
    q("Give the other player a genuine compliment, out loud, right now.", 1),
  ],
  wyd: [
    q("What would you do if you won the lottery tomorrow?", 1),
    q("What would you do if you had 24 hours where nothing was illegal?", 1),
    q("What would you do if you found out you had one year left to live?", 3),
    q("What would you do if you woke up as the opposite gender for a day?", 1),
    q("What would you do if you could switch lives with anyone for a week?", 1),
    q("What would you do if no one could see your face for a year?", 1),
    q("What would you do if you could relive your teenage years knowing what you know now?", 2),
    q("What would you do if you found a wallet with $1000 cash and an ID inside?", 1),
    q("What would you do if you had to move to a new country tomorrow, alone?", 2),
    q("What would you do if you could read one person's mind for a day?", 1),
    q("What would you do if you woke up famous overnight?", 1),
    q("What would you do if you found out your best friend lied to you about something big?", 2),
    q("What would you do if you could erase one memory forever?", 3),
    q("What would you do if you had to give a speech to thousands with no prep?", 1),
  ],
  // Vote-mode prompts: instead of typing an answer, the group votes for
  // *which player* the prompt best fits. Works with 3+ players.
  vote: [
    q("Who's most likely to become a millionaire?", 1),
    q("Who's most likely to survive a zombie apocalypse?", 1),
    q("Who's most likely to cry during a movie?", 1),
    q("Who's most likely to forget their own birthday?", 1),
    q("Who's most likely to become famous?", 1),
    q("Who's most likely to win an argument with zero evidence?", 1),
    q("Who's most likely to accidentally start a business?", 1),
    q("Who's most likely to sleep through their alarm?", 1),
    q("Who's most likely to adopt way too many pets?", 1),
    q("Who's most likely to eat the last slice without asking?", 1),
    q("Who's most likely to give the best advice?", 1),
    q("Who's most likely to get lost using GPS?", 1),
    q("Who's most likely to become a hermit?", 1),
    q("Who's most likely to talk their way out of a speeding ticket?", 1),
    q("Who's most likely to laugh at their own joke the hardest?", 1),
    q("Who's most likely to move to another country on a whim?", 1),
    q("Who's most likely to be the last one awake at a sleepover?", 1),
    q("Who's most likely to become an internet meme?", 1),
    q("Who's most likely to overthink a text message?", 1),
    q("Who's most likely to try to fix something and make it worse?", 1),
    q("Who's most likely to remember everyone's birthday?", 1),
    q("Who's most likely to become a reality TV star?", 1),
  ],
};
