// ====== Between Us — question bank ======
// Each category has a label, emoji, an "ink stamp" color (used on the
// card's corner label), and a list of questions. "mix" has no question
// list of its own — it's built by combining all categories at runtime.

export const CATEGORY_META = {
  mix: { emoji: "🎲", label: "Random Mix", color: "#c9a15a" },
  love: { emoji: "❤️", label: "Love", color: "#9c3348" },
  friendship: { emoji: "😊", label: "Friendship", color: "#2f6f65" },
  deep: { emoji: "🔥", label: "Deep", color: "#3d3a75" },
  funny: { emoji: "😂", label: "Funny", color: "#b8862e" },
  wouldYouRather: { emoji: "🧠", label: "Would You Rather", color: "#3c6b3f" },
  confessions: { emoji: "💭", label: "Confessions", color: "#6b3d6b" },
  dares: { emoji: "😈", label: "Dares", color: "#a1452a" },
  wyd: { emoji: "🤔", label: "What Would You Do", color: "#45566b" },
};

export const QUESTIONS = {
  love: [
    "What was the moment you knew you had feelings for me?",
    "What's one small thing I do that makes you feel loved?",
    "What's your love language, and do you think I speak it well?",
    "What's a memory of us you'd want to relive exactly as it happened?",
    "What's something you find attractive that most people wouldn't guess?",
    "What's a fear you have about us, if any?",
    "What's the most romantic thing you can imagine us doing?",
    "When do you feel closest to me?",
    "What's a song that reminds you of me?",
    "What's something you want us to try together that we haven't yet?",
    "What do you think is our biggest strength as a couple?",
    "What's one thing you hope never changes between us?",
    "How do you like to be comforted when you're upset?",
    "What's a habit of mine you secretly love?",
    "Where do you picture us in five years?",
    "What's something you've never told me but want to?",
  ],
  friendship: [
    "What's the first thing you noticed about me when we met?",
    "What's one thing I do that annoys you (be honest)?",
    "What's your favorite memory with me?",
    "If I disappeared tomorrow, what would you miss most?",
    "What's a quality of mine you wish you had?",
    "When did you know we'd actually be close?",
    "What's something you've never told me because it felt awkward?",
    "What's the funniest thing we've been through together?",
    "How would you describe us in three words?",
    "What's a piece of advice I gave you that actually stuck?",
    "What's something you think I'm better at than I realize?",
    "If we started a business together, what would it be?",
    "What's a habit of mine that low-key influenced you?",
    "What do you think people misunderstand about me?",
    "What's one thing you'd want to do together before we're 80?",
    "Who would play me in a movie about your life?",
  ],
  deep: [
    "What's something nobody in your life fully knows about you?",
    "What's your biggest regret so far?",
    "If today were your last day, who's the first person you'd call?",
    "What's your biggest, most honest dream?",
    "What's something you're scared of that you rarely admit?",
    "What belief did you hold strongly that you later changed your mind about?",
    "What's something you needed to hear from someone, but never did?",
    "What does \"home\" mean to you?",
    "What's a moment that quietly changed who you are?",
    "What do you think is the point of your life, if there is one?",
    "What's something you forgive yourself for now that you didn't used to?",
    "Who shaped you the most, for better or worse?",
    "What are you most proud of that no one really gave you credit for?",
    "What's a question you're afraid to ask yourself?",
    "What would you want people to say about you after you're gone?",
    "What's something you're still healing from?",
  ],
  funny: [
    "What's your most embarrassing moment that you can laugh about now?",
    "What's your weirdest habit that almost nobody knows about?",
    "Which celebrity would survive a zombie apocalypse, and why?",
    "If animals could talk, which one would be the rudest?",
    "What's the dumbest thing you've ever argued about?",
    "What's a food combination you love that grosses other people out?",
    "What's the most ridiculous excuse you've ever used?",
    "If your life had a laugh track, what moment would trigger it most?",
    "What's a weird talent you have that's basically useless?",
    "What's the worst haircut or outfit you've ever had?",
    "What's a lie you told as a kid that somehow worked?",
    "If you had a theme song that played every time you walked in, what would it be?",
    "What's the strangest dream you remember having?",
    "What's a word you can never pronounce correctly?",
    "What's the most chaotic thing that's happened on a night out?",
    "If you were a meme, which one would you be?",
  ],
  wouldYouRather: [
    "Lose your phone forever or never eat your favorite food again?",
    "Be invisible or be able to read minds?",
    "Live underwater or live on Mars?",
    "Always know when someone's lying, or always get away with lying yourself?",
    "Have unlimited money or unlimited time?",
    "Relive your favorite year or skip straight to a guaranteed happy future?",
    "Be famous for something embarrassing or unknown but respected?",
    "Never use social media again or never watch another movie or show again?",
    "Always say what you're thinking or never speak again for a day?",
    "Travel to the past or the future?",
    "Have the ability to fly or be super strong?",
    "Eat one meal for the rest of your life or never eat your favorite meal again?",
    "Live without music or live without your phone?",
    "Talk to animals or speak every human language fluently?",
    "Have a rewind button on life or a pause button?",
    "Know how you'll die or know when you'll die?",
  ],
  confessions: [
    "What's something you've done that you've never told anyone?",
    "What's a small lie you've told that turned into a bigger one?",
    "What's something you pretend to like but actually don't?",
    "What's a time you took credit for something you didn't fully do?",
    "What's something you're jealous of, even if it's silly?",
    "What's a secret talent you've never shown anyone?",
    "What's something you did as a kid that would embarrass you now?",
    "What's a rule you break more often than you'd admit?",
    "What's something you judged someone for, then realized you do too?",
    "What's the last thing you cried about?",
    "What's something you say you're fine with, but actually aren't?",
    "What's a text or message you regret sending?",
    "What's a habit you have that you're low-key trying to hide?",
    "What's something you wish you could redo differently?",
  ],
  dares: [
    "Send the last photo in your camera roll, no explanation.",
    "Do your best impression of the other player right now.",
    "Text a random contact \"I have something important to tell you,\" then leave them hanging.",
    "Speak in an accent of your choice for the next two questions.",
    "Show your most-used emoji and explain why it's your go-to.",
    "Do 10 jumping jacks before answering the next question.",
    "Let the other player post one word as your status for the next hour.",
    "Sing the chorus of the last song you listened to.",
    "Show the last thing you searched on your phone, if it's not private.",
    "Do your best dance move for 10 seconds.",
    "Let the other player scroll your camera roll for 10 seconds.",
    "Talk in slow motion for your next answer.",
    "Attempt to lick your elbow. Yes, really.",
    "Give the other player a genuine compliment, out loud, right now.",
  ],
  wyd: [
    "What would you do if you won the lottery tomorrow?",
    "What would you do if you had 24 hours where nothing was illegal?",
    "What would you do if you found out you had one year left to live?",
    "What would you do if you woke up as the opposite gender for a day?",
    "What would you do if you could switch lives with anyone for a week?",
    "What would you do if no one could see your face for a year?",
    "What would you do if you could relive your teenage years knowing what you know now?",
    "What would you do if you found a wallet with $1000 cash and an ID inside?",
    "What would you do if you had to move to a new country tomorrow, alone?",
    "What would you do if you could read one person's mind for a day?",
    "What would you do if you woke up famous overnight?",
    "What would you do if you found out your best friend lied to you about something big?",
    "What would you do if you could erase one memory forever?",
    "What would you do if you had to give a speech to thousands with no prep?",
  ],
};
