// ====== Between Us — question bank ======
// Every question now carries a "level" from 1 (light) to 4 (vulnerable).
// Levels power Conversation Mode, which orders a deck so it starts easy
// and gradually deepens instead of pure random shuffle.
//
// CATEGORY_META gives each category a label, emoji, and an "ink stamp"
// color for the card's corner label. "mix" has no question list of its
// own — it's built by combining every category at runtime.

export const CATEGORY_META = {
  mix: { emoji: "🎲", label: "Random Mix", color: "#c9a15a" },
  love: { emoji: "❤️", label: "Love", color: "#9c3348" },
  friendship: { emoji: "😊", label: "Friendship", color: "#2f6f65" },
  family: { emoji: "👨‍👩‍👧", label: "Family", color: "#a1653d" },
  deep: { emoji: "🔥", label: "Deep", color: "#3d3a75" },
  funny: { emoji: "😂", label: "Funny", color: "#b8862e" },
  party: { emoji: "🎉", label: "Party", color: "#c2437a" },
  firstImpressions: { emoji: "🎯", label: "First Impressions", color: "#4a6fa5" },
  wouldYouRather: { emoji: "🧠", label: "Would You Rather", color: "#3c6b3f" },
  confessions: { emoji: "💭", label: "Confessions", color: "#6b3d6b" },
  dares: { emoji: "😈", label: "Dares", color: "#a1452a" },
  wyd: { emoji: "🤔", label: "What Would You Do", color: "#45566b" },
  vote: { emoji: "🗳️", label: "Vote Prompts", color: "#7a4fba" },
  custompack: { emoji: "📦", label: "Custom Pack", color: "#5b6b8c" },

  vibeCheck: { emoji: "⚡", label: "Vibe Check", color: "#e056fd", explicit: true },
  dilemmas: { emoji: "🚨", label: "Hard Dilemmas", color: "#eb4d4b" },
  growth: { emoji: "🌱", label: "Deep Growth", color: "#2ecc71" },
  intimate: { emoji: "💘", label: "Intimacy", color: "#f39c12", explicit: true },
};

function q(text, level) {
  return { text, level };
}

// ===================================================================
// SINGLE, UNIFIED QUESTIONS OBJECT — everything lives inside this ONE
// export. Do NOT create a second "export const QUESTIONS = {...}"
// anywhere else in this file — that causes a fatal SyntaxError and
// freezes the entire app (this was the bug that broke the game).
// ===================================================================

export const QUESTIONS = {
  love: [
    q("What was the moment you knew you had feelings for me?", 2),
    q("What's one small thing I do that makes you feel loved?", 1),
    q("What's your love language, and do you think I speak it well?", 2),
    q("What's a memory of us you'd want to relive exactly as it happened?", 2),
    q("What's something you find attractive that most people wouldn't guess?", 2),
    q("What's a fear you have about us, if any?", 4),
    q("What's the most romantic thing you can imagine us doing?", 1),
    q("When do you feel closest to me?", 2),
    q("What's a song that reminds you of me?", 1),
    q("What's something you want us to try together that we haven't yet?", 2),
    q("What do you think is our biggest strength as a couple?", 2),
    q("What's one thing you hope never changes between us?", 2),
    q("How do you like to be comforted when you're upset?", 2),
    q("What's a habit of mine you secretly love?", 1),
    q("Where do you picture us in five years?", 3),
    q("What's something you've never told me but want to?", 4),
  ],

  friendship: [
    q("What's the first thing you noticed about me when we met?", 1),
    q("What's one thing I do that annoys you (be honest)?", 2),
    q("What's your favorite memory with me?", 1),
    q("If I disappeared tomorrow, what would you miss most?", 3),
    q("What's a quality of mine you wish you had?", 2),
    q("When did you know we'd actually be close?", 2),
    q("What's something you've never told me because it felt awkward?", 3),
    q("What's the funniest thing we've been through together?", 1),
    q("How would you describe us in three words?", 1),
    q("What's a piece of advice I gave you that actually stuck?", 2),
    q("What's something you think I'm better at than I realize?", 2),
    q("If we started a business together, what would it be?", 1),
    q("What's a habit of mine that low-key influenced you?", 2),
    q("What do you think people misunderstand about me?", 3),
    q("What's one thing you'd want to do together before we're 80?", 2),
    q("Who would play me in a movie about your life?", 1),
  ],

  family: [
    q("What's a family tradition you actually love?", 1),
    q("Who do you take after most in your family, and how?", 1),
    q("What's a rule your family had growing up that you still follow?", 1),
    q("What's your favorite family holiday memory?", 1),
    q("What's something your family does that other families would find strange?", 1),
    q("Who's the funniest person in your family?", 1),
    q("What's a lesson your parents (or whoever raised you) taught you that stuck?", 2),
    q("What's a family recipe or dish you'd never want to lose?", 1),
    q("What's something you hope to do differently than your parents did?", 3),
    q("What's your earliest childhood memory?", 2),
    q("If you could bring back one family gathering exactly as it was, which one?", 2),
    q("What's a nickname from your family you actually don't mind?", 1),
  ],

  deep: [
    q("What's something nobody in your life fully knows about you?", 4),
    q("What's your biggest regret so far?", 3),
    q("If today were your last day, who's the first person you'd call?", 3),
    q("What's your biggest, most honest dream?", 3),
    q("What's something you're scared of that you rarely admit?", 4),
    q("What belief did you hold strongly that you later changed your mind about?", 2),
    q("What's something you needed to hear from someone, but never did?", 4),
    q("What does \"home\" mean to you?", 2),
    q("What's a moment that quietly changed who you are?", 3),
    q("What do you think is the point of your life, if there is one?", 3),
    q("What's something you forgive yourself for now that you didn't used to?", 4),
    q("Who shaped you the most, for better or worse?", 3),
    q("What are you most proud of that no one really gave you credit for?", 2),
    q("What's a question you're afraid to ask yourself?", 4),
    q("What would you want people to say about you after you're gone?", 3),
    q("What's something you're still healing from?", 4),
  ],

  funny: [
    q("What's your most embarrassing moment that you can laugh about now?", 1),
    q("What's your weirdest habit that almost nobody knows about?", 1),
    q("Which celebrity would survive a zombie apocalypse, and why?", 1),
    q("If animals could talk, which one would be the rudest?", 1),
    q("What's the dumbest thing you've ever argued about?", 1),
    q("What's a food combination you love that grosses other people out?", 1),
    q("What's the most ridiculous excuse you've ever used?", 1),
    q("If your life had a laugh track, what moment would trigger it most?", 1),
    q("What's a weird talent you have that's basically useless?", 1),
    q("What's the worst haircut or outfit you've ever had?", 1),
    q("What's a lie you told as a kid that somehow worked?", 1),
    q("If you had a theme song that played every time you walked in, what would it be?", 1),
    q("What's the strangest dream you remember having?", 1),
    q("What's a word you can never pronounce correctly?", 1),
    q("What's the most chaotic thing that's happened on a night out?", 1),
    q("If you were a meme, which one would you be?", 1),
  ],

  party: [
    q("What's your go-to karaoke song?", 1),
    q("What's the best party you've ever been to?", 1),
    q("Dance floor or snack table — where do we find you?", 1),
    q("What's a party trick or talent you can pull out on command?", 1),
    q("What's the worst party foul you've ever witnessed?", 1),
    q("If tonight had a theme, what would it be?", 1),
    q("What song instantly gets you on the dance floor?", 1),
    q("What's your late-night snack of choice?", 1),
    q("Who's more likely to start a conga line — you or me?", 1),
    q("What's the most fun you've had on a random night out?", 1),
    q("If we threw a party right now, who's the first person you'd invite?", 1),
    q("What's your signature drink order (alcoholic or not)?", 1),
  ],

  firstImpressions: [
    q("What was your actual first impression of me?", 2),
    q("What do you think I noticed about you first?", 2),
    q("Did you like me right away, or did I grow on you?", 2),
    q("What almost stopped us from becoming close?", 3),
    q("What's something about me that surprised you once you got to know me?", 2),
    q("If you had to guess my job from a first meeting, what would you have guessed?", 1),
    q("What do you think strangers assume about me that's wrong?", 2),
    q("What's the first thing people usually notice about you?", 1),
    q("Would you have approached me first, or waited?", 1),
    q("What's a first impression of someone that turned out to be completely wrong?", 1),
    q("What do you remember about the outfit or vibe I had when we met?", 1),
    q("Looking back, what took you the longest to figure out about me?", 3),
  ],

  wouldYouRather: [
    q("Lose your phone forever or never eat your favorite food again?", 1),
    q("Be invisible or be able to read minds?", 1),
    q("Live underwater or live on Mars?", 1),
    q("Always know when someone's lying, or always get away with lying yourself?", 1),
    q("Have unlimited money or unlimited time?", 1),
    q("Relive your favorite year or skip straight to a guaranteed happy future?", 1),
    q("Be famous for something embarrassing or unknown but respected?", 1),
    q("Never use social media again or never watch another movie or show again?", 1),
    q("Always say what you're thinking or never speak again for a day?", 1),
    q("Travel to the past or the future?", 1),
    q("Have the ability to fly or be super strong?", 1),
    q("Eat one meal for the rest of your life or never eat your favorite meal again?", 1),
    q("Live without music or live without your phone?", 1),
    q("Talk to animals or speak every human language fluently?", 1),
    q("Have a rewind button on life or a pause button?", 1),
    q("Know how you'll die or know when you'll die?", 2),
  ],

  confessions: [
    q("What's something you've done that you've never told anyone?", 4),
    q("What's a small lie you've told that turned into a bigger one?", 2),
    q("What's something you pretend to like but actually don't?", 1),
    q("What's a time you took credit for something you didn't fully do?", 2),
    q("What's something you're jealous of, even if it's silly?", 2),
    q("What's a secret talent you've never shown anyone?", 1),
    q("What's something you did as a kid that would embarrass you now?", 1),
    q("What's a rule you break more often than you'd admit?", 2),
    q("What's something you judged someone for, then realized you do too?", 3),
    q("What's the last thing you cried about?", 3),
    q("What's something you say you're fine with, but actually aren't?", 4),
    q("What's a text or message you regret sending?", 2),
    q("What's a habit you have that you're low-key trying to hide?", 2),
    q("What's something you wish you could redo differently?", 3),
  ],

  dares: [
    q("Send the last photo in your camera roll, no explanation.", 2),
    q("Do your best impression of the other player right now.", 1),
    q("Text a random contact \"I have something important to tell you,\" then leave them hanging.", 1),
    q("Speak in an accent of your choice for the next two questions.", 1),
    q("Show your most-used emoji and explain why it's your go-to.", 1),
    q("Do 10 jumping jacks before answering the next question.", 1),
    q("Let the other player post one word as your status for the next hour.", 1),
    q("Sing the chorus of the last song you listened to.", 1),
    q("Show the last thing you searched on your phone, if it's not private.", 1),
    q("Do your best dance move for 10 seconds.", 1),
    q("Let the other player scroll your camera roll for 10 seconds.", 2),
    q("Talk in slow motion for your next answer.", 1),
    q("Attempt to lick your elbow. Yes, really.", 1),
    q("Give the other player a genuine compliment, out loud, right now.", 1),
  ],

  wyd: [
    q("What would you do if you won the lottery tomorrow?", 1),
    q("What would you do if you had 24 hours where nothing was illegal?", 1),
    q("What would you do if you found out you had one year left to live?", 3),
    q("What would you do if you woke up as the opposite gender for a day?", 1),
    q("What would you do if you could switch lives with anyone for a week?", 1),
    q("What would you do if no one could see your face for a year?", 1),
    q("What would you do if you could relive your teenage years knowing what you know now?", 2),
    q("What would you do if you found a wallet with $1000 cash and an ID inside?", 1),
    q("What would you do if you had to move to a new country tomorrow, alone?", 2),
    q("What would you do if you could read one person's mind for a day?", 1),
    q("What would you do if you woke up famous overnight?", 1),
    q("What would you do if you found out your best friend lied to you about something big?", 2),
    q("What would you do if you could erase one memory forever?", 3),
    q("What would you do if you had to give a speech to thousands with no prep?", 1),
  ],

  vote: [
    q("Who's most likely to become a millionaire?", 1),
    q("Who's most likely to survive a zombie apocalypse?", 1),
    q("Who's most likely to cry during a movie?", 1),
    q("Who's most likely to forget their own birthday?", 1),
    q("Who's most likely to become famous?", 1),
    q("Who's most likely to win an argument with zero evidence?", 1),
    q("Who's most likely to accidentally start a business?", 1),
    q("Who's most likely to sleep through their alarm?", 1),
    q("Who's most likely to adopt way too many pets?", 1),
    q("Who's most likely to eat the last slice without asking?", 1),
    q("Who's most likely to give the best advice?", 1),
    q("Who's most likely to get lost using GPS?", 1),
    q("Who's most likely to become a hermit?", 1),
    q("Who's most likely to talk their way out of a speeding ticket?", 1),
    q("Who's most likely to laugh at their own joke the hardest?", 1),
    q("Who's most likely to move to another country on a whim?", 1),
    q("Who's most likely to be the last one awake at a sleepover?", 1),
    q("Who's most likely to become an internet meme?", 1),
    q("Who's most likely to overthink a text message?", 1),
    q("Who's most likely to try to fix something and make it worse?", 1),
    q("Who's most likely to remember everyone's birthday?", 1),
    q("Who's most likely to become a reality TV star?", 1),
  ],

  vibeCheck: [
    q("If we were both single tomorrow, would you actually smash or nah?", 1),
    q("What's one physical trait of mine that lowkey makes you attracted?", 1),
    q("Do you think we have chemistry, or are we better as friends?", 1),
    q("What's the most flirty thing I've ever said to you?", 1),
    q("If you had to describe our dynamic in one word, what would it be?", 1),
    q("Have you ever caught yourself checking me out?", 1),
    q("What's your first impression been of me since day one?", 1),
    q("Do you think I'm your type, or nah?", 1),
    q("What's something about me that surprised you in a good way?", 1),
    q("If we kissed right now, would it ruin the vibe or nah?", 1),
    q("What's one thing you like about how I look?", 1),
    q("Do you ever think about me when you're alone?", 1),
    q("What's your favorite memory of us being close?", 1),
    q("Would you say you're attracted to my energy or my looks more?", 1),
    q("If you could change one thing about me physically, what?", 1),
    q("Do you think I'm sexy? Be honest.", 1),
    q("What's the vibe when we're alone together?", 1),
    q("Have I ever made you nervous in a good way?", 1),
    q("What's something I wear that looks good on me?", 1),
    q("Do you get butterflies when I'm near you?", 1),
    q("What's your honest take on how I carry myself?", 1),
    q("If you had to rate your attraction to me out of 10, what's real?", 1),
    q("What's a specific moment where you thought I was hot?", 1),
    q("Do you ever imagine what dating me would be like?", 1),
    q("What's your type, and do I fit it?", 1),
    q("Have you ever felt jealous seeing me with someone else?", 1),
    q("What's something small I do that's lowkey attractive?", 1),
    q("Do you think about me differently now than when we met?", 1),
    q("What would make you actually want to be with me?", 1),
    q("Be real - if we were both drunk right now, would anything happen?", 1),
    q("What's a specific habit I have that completely kills the vibe?", 2),
    q("If we could hook up with zero consequences, would you?", 2),
    q("What's one personality trait of mine that's genuinely attractive?", 2),
    q("Have you ever fantasized about me? What was it like?", 2),
    q("What's the most attractive thing about my personality?", 2),
    q("Would you smash me right now if I said yes?", 2),
    q("What's something sexual you've thought about with me?", 2),
    q("Do you think you could actually fall in love with me?", 2),
    q("What's a physical feature of mine that drives you crazy?", 2),
    q("If I came onto you right now, what would you do?", 2),
    q("What's your honest take on how we'd be together?", 2),
    q("Have you ever gotten hard/wet thinking about me?", 2),
    q("What's the most attractive thing I've ever done?", 2),
    q("If there were no consequences, would we actually date?", 2),
    q("What's something sexual I could do that would turn you on?", 2),
    q("Do you find yourself staring at me sometimes?", 2),
    q("What's a fantasy you've had involving me?", 2),
    q("If we made out right now, what would happen next?", 2),
    q("What's something about my body that you're attracted to?", 2),
    q("Do you ever touch yourself thinking about me?", 2),
    q("What's the difference between how you see me now vs when we met?", 2),
    q("If I started dating someone else, would you actually be bothered?", 2),
    q("What's your honest vibe - are we platonic or is there chemistry?", 2),
    q("Have you ever wanted to kiss me? When?", 2),
    q("What would I need to do to seduce you?", 2),
    q("Do you think we'd be better together or apart?", 2),
    q("What's the most intimate non-sexual thing we've done?", 2),
    q("If you could change one thing about my appearance, what and why?", 2),
    q("What's your take - are you into me or nah?", 2),
    q("Have you ever gotten jealous over me? What happened?", 2),
    q("What's something I wear that makes you look twice?", 2),
    q("Do you think about me sexually? How often?", 2),
    q("If we were dating, what would be the first thing you'd do with me?", 2),
    q("What's the sexiest version of me you've ever seen?", 2),
    q("Be honest - would you regret hooking up with me or nah?", 2),
    q("What scares you most about potentially falling for me?", 3),
    q("If you could change one thing about me to be more into me, what?", 3),
    q("Do you think your feelings for me could go deeper?", 3),
    q("What would I need to do or say to make you fall for me?", 3),
    q("What's a secret attraction you have that you've never told anyone?", 3),
    q("If you could be with me, what's holding you back?", 3),
    q("What's something about your sexuality that you're scared to admit?", 3),
    q("Do you genuinely think we could work, or are you just saying that?", 3),
    q("What's your biggest insecurity about being with me?", 3),
    q("If I said I had feelings for you, how would you actually react?", 3),
    q("What's the real reason you're not with me?", 3),
    q("Do you think you're good enough for me?", 3),
    q("What's something you want sexually that you're too scared to ask for?", 3),
    q("If we got together, what would you be most worried about?", 3),
    q("What's a part of yourself you hide because you think I'd judge?", 3),
    q("Have you ever felt like you're not enough for me physically?", 3),
    q("What would need to change for us to actually be together?", 3),
    q("If I wasn't in your life, what would you miss most?", 3),
    q("What's the most vulnerable you've ever felt around me?", 3),
    q("Do you think you could be faithful to me if we dated?", 3),
    q("What's something about me that intimidates you?", 3),
    q("If you could have me for just one night, would you?", 3),
    q("What's your biggest fear about being in love with me?", 3),
    q("Do you think I'm out of your league?", 3),
    q("What's something sexual that would make you feel vulnerable?", 3),
    q("If I rejected you, how would that actually make you feel?", 3),
    q("What's holding you back from being real with me about attraction?", 3),
    q("Do you think you'd regret not being with me?", 3),
    q("What's the most honest thing you've never told me?", 3),
    q("If you could be someone else to be with me, would you?", 3),
    q("What's a dealbreaker for you that I might not know about?", 3),
    q("Do you think about me more than you think about your current situation?", 3),
    q("What's something you want from me that you're afraid to ask?", 3),
    q("If we couldn't tell anyone about us, would you still want it?", 3),
    q("What's the real truth about how you feel?", 3),
    q("Are we actually in love with each other but too scared to admit it?", 4),
    q("If there were zero consequences, would you choose me over everything?", 4),
    q("What's the honest reason you're not with me right now?", 4),
    q("Do you actually think we could work, or are you lying?", 4),
    q("If you had to choose between me and your comfort, what would you do?", 4),
    q("What's the one thing that would make you actually commit to me?", 4),
    q("Are you in love with me but scared to show it?", 4),
    q("What's the real barrier between us?", 4),
    q("If I left your life forever, would you actually regret it?", 4),
    q("Do you think we're soulmates or just passing chemistry?", 4),
    q("What would it take for you to fully choose me?", 4),
    q("Is the only thing stopping us logistics, or is there more?", 4),
    q("Do you love me, or do you love the idea of me?", 4),
    q("What's your honest answer about our future together?", 4),
    q("If you could have me tomorrow, would you take it?", 4),
    q("What's the lie you've been telling me about how you feel?", 4),
    q("Are we destined for this or just convenient?", 4),
    q("Do you think about a future with me?", 4),
    q("What would make you brave enough to actually choose this?", 4),
    q("Be completely honest - do you see me as your person?", 4),
  ],

  dilemmas: [
    q("If I got drunk and flirted with someone at a party, could you get over it?", 1),
    q("Would you forgive me if I accidentally texted your ex?", 1),
    q("If I lied to protect your feelings, would you want the truth?", 1),
    q("Would you be okay if I had a close friendship with an ex?", 1),
    q("What's a small lie that would bother you more than a big one?", 1),
    q("If I didn't tell you about hanging out with someone, would that be cheating?", 1),
    q("Would you be mad if I followed my ex on social media?", 1),
    q("If I forgot an important date, could you forgive me easily?", 1),
    q("Would it bother you if I went out without telling you where?", 1),
    q("If I made a joke that hurt your feelings, how would you handle it?", 1),
    q("Would you forgive me if I was late to something important?", 1),
    q("If I accidentally liked an old ex's photo, would you care?", 1),
    q("Would you be upset if I spent time with someone you didn't like?", 1),
    q("If I forgot to text you back for hours, would you assume the worst?", 1),
    q("Would you forgive me if I made a big purchase without asking?", 1),
    q("If I was flirty in a group setting, would you be bothered?", 1),
    q("Would you care if I went to a party without you?", 1),
    q("If I made plans and canceled last minute, how bad is that?", 1),
    q("Would you forgive me for an accidental white lie?", 1),
    q("If I didn't introduce you to someone I know, would that hurt?", 1),
    q("Would you be mad if I had a close friend of the gender I'm attracted to?", 1),
    q("If I made a mistake at work and vented to someone else first, would you care?", 1),
    q("Would you forgive me if I was insensitive without meaning to be?", 1),
    q("If I didn't remember something you told me, would you hold it against me?", 1),
    q("Would you be upset if I spent more money on myself than on you?", 1),
    q("If I forgot your birthday but remembered it later, could you get over it?", 1),
    q("Would you care if I complimented someone else's appearance?", 1),
    q("If I was on my phone a lot around you, would you feel bad?", 1),
    q("Would you forgive me for canceling plans for something better?", 1),
    q("If I made a joke about your insecurity, would you actually forgive me?", 1),
    q("If I was emotionally close to someone else, would that count as cheating?", 2),
    q("Would you forgive me if I kept a friendship secret because I thought you'd be upset?", 2),
    q("If you found out I still had feelings for an ex, what would you do?", 2),
    q("What's your actual breaking point in a relationship?", 2),
    q("If I prioritized my career over us for a year, could you handle it?", 2),
    q("Would you stay if I couldn't give you kids?", 2),
    q("If I got close to someone emotionally but nothing physical happened, is that cheating?", 2),
    q("Would you forgive me if I talked shit about you to my friends?", 2),
    q("If I went to a party and didn't mention someone attractive being there, would you care?", 2),
    q("Would you leave me if I lied about something big?", 2),
    q("If I was messaging an ex 'just as friends', would you trust it?", 2),
    q("Would you forgive me if I put you down in front of people?", 2),
    q("If I had a crush on someone we both know, what would you do?", 2),
    q("Would you stay with me if my mental health got really bad?", 2),
    q("If I didn't want to introduce you to my family, would you end it?", 2),
    q("Would you forgive me if I was selfish during an important moment?", 2),
    q("If I was actively hiding something from you, would you notice?", 2),
    q("Would you leave me over a fundamental value difference?", 2),
    q("If I had feelings for someone but didn't act on them, should I tell you?", 2),
    q("Would you forgive me if I prioritized myself over our relationship?", 2),
    q("If I was secretive about my phone, would you get suspicious?", 2),
    q("Would you stay if I wasn't attracted to you anymore?", 2),
    q("If I needed space and just disappeared for a bit, could you handle it?", 2),
    q("Would you forgive me if I was toxic in a moment of stress?", 2),
    q("If I was still in contact with someone I hooked up with, would that bother you?", 2),
    q("Would you leave me if I cheated emotionally?", 2),
    q("If I lied about where I was, would you immediately assume the worst?", 2),
    q("Would you forgive me if I exposed your secrets to someone?", 2),
    q("If I wasn't happy but stayed anyway, would you want to know?", 2),
    q("Would you stay if I got addicted to something?", 2),
    q("If I was slowly pulling away, would you fight for us?", 2),
    q("Would you forgive me if I made you feel small in public?", 2),
    q("If I had to choose between you and something important to me, what would you expect?", 2),
    q("Would you leave me if we wanted different things in life?", 2),
    q("If I was emotionally unavailable for a long time, could you stay?", 2),
    q("If I physically cheated but it meant nothing, could you forgive me? What if it meant something?", 3),
    q("Have you ever considered leaving me? What was the reason?", 3),
    q("If I was unfaithful, would you want to work through it or leave?", 3),
    q("What would you need from me to feel safe again if I broke your trust?", 3),
    q("Is there anything I could do that would be unforgivable?", 3),
    q("If you fell in love with someone else while with me, what would you do?", 3),
    q("Would you tell me if you cheated, or would you take it to the grave?", 3),
    q("If I found out you lied about something huge, could we come back from it?", 3),
    q("What's a dealbreaker that would make you leave no matter what?", 3),
    q("If I was abusive in any way, would you leave immediately?", 3),
    q("Have you ever wanted to leave but stayed anyway?", 3),
    q("If I didn't support your dreams, would you eventually resent me?", 3),
    q("Would you tell me the truth if you were unhappy, or just pretend?", 3),
    q("If you caught me talking to an ex in a flirty way, would that be it?", 3),
    q("Is there something you've done that you think would make me leave?", 3),
    q("If I abandoned you during a crisis, could you forgive me?", 3),
    q("Would you leave me if you found out I was being fake the whole time?", 3),
    q("If I got caught in a huge lie, could we rebuild from there?", 3),
    q("What's the biggest betrayal you could never forgive?", 3),
    q("If I cheated and felt guilty but never told you, should you know?", 3),
    q("Would you leave me if I refused to get help for a problem?", 3),
    q("If you discovered I was the one who messed something up (not me telling you), how bad?", 3),
    q("Is there a limit to how many chances you'd give me?", 3),
    q("If I was talking to multiple people romantically, would we be done?", 3),
    q("Would you leave me if my family hated you and I chose them?", 3),
    q("If I lost all motivation and couldn't get it back, would you stay?", 3),
    q("Would you forgive me if I was honest about a betrayal?", 3),
    q("If I did something that broke your trust permanently, could you move on?", 3),
    q("What's the one thing I've done or could do that would actually hurt too much?", 3),
    q("If I was keeping a huge secret, would you want to know even if it ruins us?", 3),
    q("Would you leave me if I wasn't who you thought I was?", 3),
    q("If you caught me planning to cheat, what would happen?", 3),
    q("Is there a point where you'd give up on us?", 3),
    q("If I was slowly emotionally cheating and didn't realize it, could you forgive it?", 3),
    q("What's your honest assessment - could we survive a major betrayal?", 3),
    q("Are you actually happy in this relationship, or are you staying out of comfort?", 4),
    q("What resentment have you been holding that we've never discussed?", 4),
    q("If we broke up tomorrow, what's the honest reason?", 4),
    q("Do you think we can actually survive what we've been through?", 4),
    q("What's the one thing I could never forgive you for?", 4),
    q("Are you with me because you want to be or because you're afraid to leave?", 4),
    q("If you could go back, would you still choose this relationship?", 4),
    q("What's the lie you've been telling yourself about us?", 4),
    q("Do you actually see a future with me, or are you just going through the motions?", 4),
    q("What would have to happen for you to actually leave?", 4),
    q("Are we actually compatible, or have we just gotten comfortable?", 4),
    q("What's something you've never told me that would change everything?", 4),
    q("If you had to be completely honest about our relationship right now, what would you say?", 4),
    q("Do you love me, or have you fallen out of love but stayed anyway?", 4),
    q("What's the biggest way I've let you down that you've never vocalized?", 4),
    q("Is there someone else, or is it just that you don't want me anymore?", 4),
    q("What would it take for you to leave?", 4),
    q("Do you genuinely think we can fix this, or are we fooling ourselves?", 4),
    q("What's the truth you're too scared to tell me?", 4),
    q("Are we actually meant to be, or have we been running on fumes?", 4),
  ],

  growth: [
    q("What's something about yourself you're actively trying to change?", 1),
    q("When was the last time you felt genuinely proud of yourself?", 1),
    q("What's a fear that keeps you up at night?", 1),
    q("If you could give your younger self one piece of advice, what?", 1),
    q("What's something people assume about you that's completely wrong?", 1),
    q("What's your biggest insecurity right now?", 1),
    q("When do you feel most like yourself?", 1),
    q("What's something you pretend to be confident about but actually aren't?", 1),
    q("What's your biggest goal that nobody knows about?", 1),
    q("What's something you're jealous of when you see others have it?", 1),
    q("What did you want to be as a kid?", 1),
    q("What's changed the most about you since you were younger?", 1),
    q("What's something you're good at that you don't give yourself credit for?", 1),
    q("What's a habit you hate about yourself?", 1),
    q("When did you first feel like an adult?", 1),
    q("What's something you're addicted to even though you know it's not good?", 1),
    q("What do you want people to remember about you?", 1),
    q("What's a mistake that changed your life?", 1),
    q("What's your biggest strength?", 1),
    q("When was the last time you cried and why?", 1),
    q("What's something you do when you're alone that you wouldn't do around others?", 1),
    q("What's the most embarrassing thing about you?", 1),
    q("What's something you're weirdly good at?", 1),
    q("What makes you feel alive?", 1),
    q("What's a skill you wish you had?", 1),
    q("What does your ideal day look like?", 1),
    q("What's something you're learning about yourself right now?", 1),
    q("What's your biggest accomplishment?", 1),
    q("What scares you most about the future?", 1),
    q("What's something you've never told anyone?", 1),
    q("What part of yourself do you hide from the world, and why?", 2),
    q("What's a toxic pattern you keep repeating?", 2),
    q("What do you want to be remembered for when you die?", 2),
    q("What's the most shameful thing you've ever done?", 2),
    q("Did you ever make amends for it?", 2),
    q("What would you do if you knew you couldn't fail?", 2),
    q("What's something you're deeply insecure about that nobody knows?", 2),
    q("What's a dream you've completely given up on?", 2),
    q("What's the biggest lie you've told yourself?", 2),
    q("When did you feel most betrayed?", 2),
    q("What's something about your family that messed you up?", 2),
    q("What's a wound that you haven't fully healed from?", 2),
    q("What would your life look like if you weren't afraid?", 2),
    q("What's something you do to numb yourself?", 2),
    q("What's a coping mechanism that's actually destroying you?", 2),
    q("When did you first realize you were traumatized?", 2),
    q("What's a belief you have about yourself that might be wrong?", 2),
    q("What's the biggest risk you've ever taken?", 2),
    q("Did it pay off?", 2),
    q("What's something you regret deeply?", 2),
    q("Would you change it if you could?", 2),
    q("What's your relationship with your body like?", 2),
    q("When did you stop loving yourself?", 2),
    q("What's an addiction you're hiding?", 2),
    q("What makes you feel genuinely loved?", 2),
    q("What's something you're avoiding dealing with?", 2),
    q("What would change if you actually faced your fears?", 2),
    q("What's the scariest version of yourself?", 2),
    q("What's a lesson you had to learn the hard way?", 2),
    q("What's holding you back from being your best self?", 2),
    q("What's something that happened to you that you haven't processed?", 2),
    q("What's a version of yourself that you've killed off?", 2),
    q("What's the most honest thing you could say right now?", 2),
    q("What's something you need to forgive yourself for?", 2),
    q("What's a power you didn't know you had until recently?", 2),
    q("What's a belief you hold that you know might be wrong but can't let go of?", 3),
    q("What do you think is your biggest character flaw, and how does it hurt people?", 3),
    q("When was the last time you genuinely felt broken, and are you still healing?", 3),
    q("What version of yourself do you need to become to achieve your biggest dream?", 3),
    q("Is there someone you've never fully forgiven, including yourself?", 3),
    q("What part of your past are you still running from?", 3),
    q("What if everything you believe about yourself is a lie?", 3),
    q("When did you start feeling like you weren't enough?", 3),
    q("What's a trauma that shaped who you are?", 3),
    q("Have you ever hurt someone in a way you couldn't repair?", 3),
    q("What's something you've done that you can't forgive yourself for?", 3),
    q("What does self-sabotage look like for you?", 3),
    q("When do you feel most like a fraud?", 3),
    q("What's a truth about yourself that you're terrified to face?", 3),
    q("What would happen if you actually believed you were worthy?", 3),
    q("What's a version of yourself that you killed to survive?", 3),
    q("When did you stop fighting for what you wanted?", 3),
    q("What's something you want but feel like you don't deserve?", 3),
    q("What's the deepest wound you carry?", 3),
    q("If you could go back and undo one decision, would you?", 3),
    q("What's something you've been denying about yourself?", 3),
    q("What pattern is destroying your life but you can't stop?", 3),
    q("When was the last time you felt truly seen?", 3),
    q("What's a way you self-destruct?", 3),
    q("What would you need to believe to actually change?", 3),
    q("What's a secret you're carrying that's eating you alive?", 3),
    q("What if you're not the person you think you are?", 3),
    q("What's something about you that nobody would guess?", 3),
    q("What would it take for you to actually love yourself?", 3),
    q("What's the story you tell yourself that's holding you back?", 3),
    q("When did you give up on yourself?", 3),
    q("What's a power inside you that you're afraid to use?", 3),
    q("What would change if you stopped waiting for permission?", 3),
    q("What's the grief you haven't processed?", 3),
    q("What's a version of yourself you need to let die?", 3),
    q("What would it take for you to completely reinvent yourself?", 4),
    q("Are you living the life you actually want or the life you think you should?", 4),
    q("What truth about yourself have you been avoiding?", 4),
    q("If you could go back and change one major life decision, would you?", 4),
    q("What's the most important thing you've learned about yourself?", 4),
    q("Are you actually happy, or are you just going through the motions?", 4),
    q("What would happen if you fully accepted yourself?", 4),
    q("What's holding you back from becoming who you want to be?", 4),
    q("If nothing changed about your life, would you be okay with that?", 4),
    q("What's the biggest lie you've been telling yourself?", 4),
    q("Do you actually deserve the life you want?", 4),
    q("What would you do if you truly believed in yourself?", 4),
    q("Are you running toward something or away from something?", 4),
    q("What's the real reason you haven't changed yet?", 4),
    q("If your life is a story, what chapter are you in?", 4),
    q("What's your purpose, and are you living it?", 4),
    q("Do you think you'll regret not doing something?", 4),
    q("What does genuine happiness look like for you?", 4),
    q("What's the hardest truth you have to accept?", 4),
    q("Who do you want to become, and are you brave enough?", 4),
  ],

  intimate: [
    q("What's your favorite memory of us being physically close?", 1),
    q("What's something I do that makes you feel completely safe?", 1),
    q("Do you like when I take the lead or do you prefer to?", 1),
    q("What's a small physical touch that makes you feel loved?", 1),
    q("When was the first time you felt attracted to me?", 1),
    q("What's your favorite way to be kissed?", 1),
    q("Do you like cuddles or do you get hot?", 1),
    q("What's the sexiest outfit I've worn?", 1),
    q("Do you prefer morning sex or night sex?", 1),
    q("What's a way I touch you that drives you crazy?", 1),
    q("Do you like being the big spoon or little spoon?", 1),
    q("What's your favorite position?", 1),
    q("When did you first want to sleep with me?", 1),
    q("What's something playful you want to try?", 1),
    q("Do you feel comfortable being naked around me?", 1),
    q("What's the hottest thing I've ever done?", 1),
    q("Do you like rough or gentle?", 1),
    q("What's something I do that turns you on instantly?", 1),
    q("Do you get turned on easily by me?", 1),
    q("What's a fantasy that doesn't feel too crazy?", 1),
    q("Do you like when I initiate or do you prefer to?", 1),
    q("What's your ideal foreplay?", 1),
    q("Do you feel sexy around me?", 1),
    q("What's a way I could seduce you right now?", 1),
    q("Do you like it slow or fast?", 1),
    q("What's the most intimate thing we've done?", 1),
    q("Do you get wet/hard easily thinking about me?", 1),
    q("What's your favorite time to have sex?", 1),
    q("Do you like being watched?", 1),
    q("What's something simple that gets you going?", 1),
    q("What's something you want more of physically that you've never told me?", 2),
    q("Have I ever done something in bed that surprised you in a good way?", 2),
    q("What's a fantasy you've thought about but never shared?", 2),
    q("When was a moment you felt completely vulnerable and loved?", 2),
    q("What part of your body do you wish I'd touch more?", 2),
    q("Do you ever masturbate thinking about me?", 2),
    q("What's something sexually that would make you feel confident?", 2),
    q("Have you ever faked an orgasm with me? Why?", 2),
    q("What's something you want to try that feels slightly risky?", 2),
    q("Do you like being dominant or submissive?", 2),
    q("What's something that turns you off that I do?", 2),
    q("Would you want me to be more aggressive?", 2),
    q("What's a kink you're curious about?", 2),
    q("Do you like being called names in bed?", 2),
    q("What's your biggest turn-on?", 2),
    q("Would you want to try something new with me?", 2),
    q("What's a sexual situation that makes you nervous?", 2),
    q("Do you orgasm easily with me or is it hard?", 2),
    q("What's something sexually that would blow your mind?", 2),
    q("Do you watch porn? What kind?", 2),
    q("Have you ever thought about someone else while with me?", 2),
    q("What's your ideal sex schedule?", 2),
    q("Do you feel pressured to perform?", 2),
    q("What's a sexual experience you regret?", 2),
    q("Would you want to try roleplay?", 2),
    q("What's something that would make you feel desired?", 2),
    q("Do you feel comfortable asking for what you want?", 2),
    q("What's a sexual boundary you have that I don't know about?", 2),
    q("Would you want to experiment with more toys?", 2),
    q("What's something sexually that makes you laugh?", 2),
    q("Do you feel like yourself when we're intimate?", 2),
    q("What's a fantasy that feels too taboo to say out loud?", 2),
    q("Would you want me to be more vocal?", 2),
    q("What's something that would make sex more exciting for you?", 2),
    q("Do you feel like I actually listen to your needs?", 2),
    q("What's an insecurity you have about your body that you've never told me?", 3),
    q("Is there something I do sexually that makes you uncomfortable?", 3),
    q("What would make you feel truly desired by me?", 3),
    q("Have you ever felt ashamed about wanting something sexually?", 3),
    q("What's the most intimate thing you want to experience with me that scares you?", 3),
    q("Do you worry about not being enough sexually?", 3),
    q("What's something you're afraid I'd judge you for?", 3),
    q("Have you ever had sexual trauma that affects us now?", 3),
    q("What's a sexual experience that messed you up?", 3),
    q("Do you feel pressure to want sex when I do?", 3),
    q("What's something sexually that you're ashamed of?", 3),
    q("Would you want to try something that scares you together?", 3),
    q("What's a sexual desire that feels too weird to ask for?", 3),
    q("Do you ever feel disconnected from your body during sex?", 3),
    q("What's something sexually that would make you feel vulnerable?", 3),
    q("Have you ever felt coerced into sex?", 3),
    q("What's a sexual fantasy that feels too dark?", 3),
    q("Do you feel like your body is yours when we're together?", 3),
    q("What's something sexually you're working through?", 3),
    q("Would you tell me if you weren't enjoying something?", 3),
    q("What's a sexual insecurity that haunts you?", 3),
    q("Do you feel safe being completely vulnerable with me sexually?", 3),
    q("What's a past sexual experience that still affects you?", 3),
    q("Would you want to explore BDSM?", 3),
    q("What's something sexually that would make you feel truly seen?", 3),
    q("Do you ever feel like a performance vs authentic?", 3),
    q("What's a sexual boundary that's hard for you to communicate?", 3),
    q("Have you ever wanted to tell me 'no' but didn't?", 3),
    q("What's your biggest sexual fear?", 3),
    q("Do you feel connected to me after sex or disconnected?", 3),
    q("What's something sexually that would heal you?", 3),
    q("Would you want to talk about sexual needs more?", 3),
    q("What's a sexual experience you want to have with me?", 3),
    q("Do you think we're sexually compatible?", 3),
    q("What's the most honest thing about your sexuality?", 3),
    q("Do you actually feel satisfied in our physical relationship?", 4),
    q("Are you holding back sexually from me?", 4),
    q("What's something you want to try that feels too vulnerable to ask?", 4),
    q("Are you attracted to me now the way you were at the beginning?", 4),
    q("What would make you feel more emotionally connected during sex?", 4),
    q("Is there any part of me you've learned to love that intimidated you initially?", 4),
    q("Do you feel like you can be completely yourself sexually with me?", 4),
    q("What's the honest state of our sexual connection right now?", 4),
    q("Would you leave me if our sex life was bad forever?", 4),
    q("What's a sexual need that you think will never be met?", 4),
    q("Do you think about having sex with someone else?", 4),
    q("Is our physical connection strong enough to survive harder times?", 4),
    q("What would need to change for you to feel truly satisfied?", 4),
    q("Are you genuinely fulfilled by our intimacy?", 4),
    q("What's the deepest sexual desire you have that you haven't shared?", 4),
    q("Do you feel like I know the real you sexually?", 4),
    q("What would make you feel completely seen in bed?", 4),
    q("Are we actually compatible sexually for the long term?", 4),
    q("What's the most vulnerable you've ever felt physically?", 4),
    q("Do you want our sex life to evolve? How?", 4),
  ],
};

// ===================================================================
// HELPER FUNCTIONS
// ===================================================================

export function getDeckRecommendation(relationshipStage) {
  const recommendations = {
    strangers: ["icebreaker", "dares"],
    friends: ["confessions", "vibeCheck"],
    dating: ["love", "dilemmas", "growth"],
    closePartners: ["intimate", "dilemmas", "deep"],
    married: ["intimate", "growth", "dilemmas"],
  };
  return recommendations[relationshipStage] || ["icebreaker"];
}

export function getLevelLabel(level) {
  const labels = {
    1: "Getting Started ⭐",
    2: "Getting Real ⭐⭐",
    3: "Getting Vulnerable ⭐⭐⭐",
    4: "All In ⭐⭐⭐⭐"
  };
  return labels[level] || "Unknown";
}

export function getQuestionCount() {
  let count = 0;
  for (const category in QUESTIONS) {
    if (Array.isArray(QUESTIONS[category])) {
      count += QUESTIONS[category].length;
    }
  }
  return count;
}
